spring:
  application:
    name: spring-data-jpa

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: vvv2002tb

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
